{
 "title": "EventForge dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Ресурсы сервера", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Процент загрузки процессора (CPU)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (job) (rate(dotnet_process_cpu_time_seconds_total{job=~\"eventforge.*\"}[1m])) * 100",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dotnet_exceptions_total{}", "legendFormat": "{{error_type}}" }
   ]
  },
  {
   "title": "Объем ОЗУ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (dotnet_process_memory_working_set_bytes{job=~\"eventforge.*\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Активные потоки",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job) (rate(dotnet_thread_pool_thread_count_total{job=~\"eventforge.*\"}[1m]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "HTTP работа", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Latency (p50, p95, p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_request_duration_seconds_bucket[$__rate_interval])) by (le, job, http_response_status_code))",
     "legendFormat": "{{job}} - {{http_response_status_code}} - p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_request_duration_seconds_bucket[$__rate_interval])) by (le, job, http_response_status_code))",
     "legendFormat": "{{job}} - {{http_response_status_code}} - p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_request_duration_seconds_bucket[$__rate_interval])) by (le, job, http_response_status_code))",
     "legendFormat": "{{job}} - {{http_response_status_code}} - p99"
    }
   ]
  },
  {
   "title": "Текущее количество запросов в обработке",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    { "expr": "http_server_active_requests", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Throughput (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count[$__rate_interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}